### ISSUE TITLE
How to Obtain C16 and TCGA patches

### ISSUE THREAD

**Issue by bryanwong17** [HHHedo/IBMIL#13]
Hi @HHHedo , could you guide me on how to obtain exactly the same C16 and TCGA patches as in your experiment? Could you please share the code for preprocessing WSIs into patches for the C16 dataset? There are approximately 2.8 million patches in total at 20× magnification, with about 7,200 patches per bag

Moreover, is it true that you downloaded TCGA patches from here (provided by DSMIL authors)? [TCGA Lung Tree](https://drive.google.com/file/d/17zCn-WRNzxxxh8kkdBTbDLDZy0XZ3RIu/view) I tried to download it, but it always fails, even though I have made sure I have more than 60 GB of free space.

Looking forward to your reply!

**Comment by HHHedo** [comment]
For C16, the code for preprocessing WSIs is based on [this](https://github.com/deroneriksson/python-wsi-preprocessing), which I think is the same as CLAM. Since my pre-processing was done almost 4 years ago, I can not remember the specific settings. 
For TCGA patches, I succeed in downloading them from DSMIL.
From my perspective, it is really difficult to align with others' pre-processing. So I just reproduce all the other work each time based on their original code base.
