### ISSUE TITLE
About pre-computed features

### ISSUE THREAD

**Issue by jjjharden** [HHHedo/IBMIL#2]
Hi, I am trying to implement your code.The input image size of CTransPath is 224×224, but you mentioned in your paper that the image size you used is 256×256, how did you handle it when calculating the features?

**Comment by HHHedo** [comment]
Hi, we just use `transforms.Resize(224)` in computing features.

**Comment by jjjharden** [comment]
![1](https://user-images.githubusercontent.com/109189934/232662071-b6e3fdf4-2d7d-4ea1-ac08-6aa727a992df.png)
Hi, here is the pre-computed features I obtained using Ctranspath, but the result of training the MIL aggregator with this pre-computed features is very poor.Is the data for this pre-computed features correct?

**Comment by HHHedo** [comment]
> ![1](https://user-images.githubusercontent.com/109189934/232662071-b6e3fdf4-2d7d-4ea1-ac08-6aa727a992df.png) Hi, here is the pre-computed features I obtained using Ctranspath, but the result of training the MIL aggregator with this pre-computed features is very poor.Is the data for this pre-computed features correct?

Hi, the effectiveness of CTransPath has been validated in many papers. You may directly leave an issue in [CTransPath's official github](https://github.com/Xiyue-Wang/TransPath). For your features, I empirically sample some slides and find the features are around [-1,1], but your features are near 0 (which may be caused by random initialization). Please make sure you correctly load the pre-trained weights and extract the features following [dsmil](https://github.com/binli123/dsmil-wsi/blob/master/compute_feats.py).

**Comment by jjjharden** [comment]
Thanks a lot!
